language: r

os:
  #- windows
  # - linux 
  - osx
  
r:
  - release
  # - devel

# Copied from broom
# sudo: required
# cache: packages  
bioc_required: true
warnings_are_errors: false

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    # - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"
    

  
r_binary_packages:
  - rstanarm
  - rstan
  
r_packages:
  - rlang
  - bindrcpp

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
  
after_success:
  # - Rscript -e 'covr::codecov()'
  - travis_wait 30 Rscript -e 'covr::codecov()'
  
  
  
# Copied from https://github.com/mbjoseph/minimal-rstan-travis/blob/master/.travis.yml
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-7

  
# before_install:
#   - mkdir -p ~/.R/
#   - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
#   - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations # # # # -Wno-attributes -O3" >> ~/.R/Makevars

# install: 
#   - R -e "install.packages('rstan')"